title: Arthur Selle Jacobs
email: asjacobs@inf.ufrgs.br
description: Personal website
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://asjacobs92.github.com'
theme_color: '#434341'
twitter_username: asjacobs92
github_username: asjacobs92
author: Arthur Selle Jacobs
logo: assets/images/icon.png
twitter:
  username: asjacobs92
social:
  name: Arthur Selle Jacobs
  links:
    - https://twitter.com/asjacobs92
    - https://github.com/asjacobs92
    - https://www.linkedin.com/in/asjacobs92/
    - https://scholar.google.com.br/citations?user=V8cyM_4AAAAJ&hl=en
    - https://www.researchgate.net/profile/Arthur_Jacobs2

languages: ['en']

google_analytics: UA-128184603-1

### Build settings
markdown: kramdown
minify_html: false
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - _files
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
